id: pangenome_variant_call
description: Benchmark variant callers on pangenome versus linear genome
version: 0.1
benchmarker: "Monica Aguila i Sans, Jakob Nybo Andersen, Emilie Sofie Engdal"
benchmark_yaml_spec: 0.04
software_backend: host
software_environments:
    generic:
      description: "Default environment"
      conda: "envs/generic.yml"
      envmodule: generic
      
    sawfish:
      description: "Placeholder evaluation environment"
      conda: "envs/sawfish.yml"
      envmodule: sawfish
      apptainer: "/home/monica/longread_graph_benchmarking/sawfish_0.12.10.sif"
stages:
  - id: data
    modules:
      - id: linear
        name: "cram files from linear reference"
        software_environment: "generic"
        repository: 
          url: "/home/jakni/code/pangenome_benchmark"
          commit: master
        parameters:
          - values: ["--input_dir", "input"]
    outputs:
     - id: data.linear
       path: "{dataset}.cram"

  - id: calling
    modules:
     - id: sawfish
       name: "call using sawfish"
       software_environment: "sawfish"
       repository:
         url: "/home/jakni/code/pangenome_benchmark"
         commit: master
    inputs:
     - entries:
       - data.linear
    outputs:
      id: sawfish.vcf
      path: "{dataset}.vcf"
           
